<?php

/**
 * BasePost
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $title
 * @property string $body
 * 
 * @method integer getId()    Returns the current record's "id" value
 * @method string  getTitle() Returns the current record's "title" value
 * @method string  getBody()  Returns the current record's "body" value
 * @method Post    setId()    Sets the current record's "id" value
 * @method Post    setTitle() Sets the current record's "title" value
 * @method Post    setBody()  Sets the current record's "body" value
 * 
 * @package    blog
 * @subpackage model
 * @author     Yuya Takeyama
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePost extends sfDoctrineMasterSlaveRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('post');
        $this->hasColumn('id', 'integer', null, array(
             'primary' => true,
             'unsigned' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('title', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('body', 'string', null, array(
             'type' => 'string',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}